### ISSUE TITLE
Simplify getting the token

### ISSUE THREAD

**Issue by sindresorhus** [hzoo/contributors-on-github#3]
See: https://github.com/sindresorhus/notifier-for-github-chrome/issues/57

**Comment by hzoo** [comment]
Interesting.. although it's weird in chrome app samples that they just put the client id/secret right there https://github.com/GoogleChrome/chrome-app-samples/blob/master/samples/github-auth/index.js#L9-L14 (how would you do so otherwise without a backend?)

**Comment by sindresorhus** [comment]
// @ImJasonH

**Comment by hzoo** [comment]
Ah and this is because it only gives you a code and you need a separate xhr to get the actual token: https://github.com/GoogleChrome/chrome-app-samples/blob/e347c538e8612aa3b0f90bde0fc721c4f0569125/samples/github-auth/index.js#L69-L77

> GitHub's OAuth implementation supports the standard authorization code grant type. Developers should implement the web application flow described below to obtain an authorization code and then exchange it for a token. (The implicit grant type is not supported.)

**Comment by ImJasonH** [comment]
The client ID and secret are also only usable with your specified callback URL, like `https://YOUR_EXTENSION_ID.chromiumapp.org`, which then redirects to your extension.

Attempting to use a different callback URL will fail before requesting the user's permission.

**Comment by hzoo** [comment]
Hmm alright so I guess this is just how you do it for a chrome extension then? Will try to get this in then, since getting an access token can be annoying

**Comment by hzoo** [comment]
Done with https://github.com/hzoo/contributors-on-github/issues/9!
