### ISSUE TITLE
Closing "Use OAuth" window outputs [object Object] in orange feedback bar below input

### ISSUE THREAD

**Issue by janpio** [hzoo/contributors-on-github#30]
When you close the "Use OAuth" window with the "X" button (top right), this happens:

![image](https://user-images.githubusercontent.com/183673/64196136-75913900-ce83-11e9-97e3-0babc88225f6.png)

**Comment by janpio** [comment]
From look at the code, this seems to be setting this value:

https://github.com/hzoo/contributors-on-github/blob/018a5eedc53129674435fff697be815587a68357/src/auth.js#L85-L87

In Firefox this `message` indeed seems to be a simple string:
```
Error: "User cancelled or denied access."
```

But in Chrome it seems to be an object now:
![image](https://user-images.githubusercontent.com/183673/64203590-18ea4a00-ce94-11e9-877b-494c001c176f.png)

Not sure how to properly fix this.

**Comment by mgol** [comment]
How about:
```js
document.querySelector("#feedback").textContent = message.message
  ? `Error: ${message.message}`
  : message;
```

**Comment by hzoo** [comment]
Sounds good @mgol!
