### ISSUE TITLE
Still working for anyone? (Update: Currently broken unfortunately)

### ISSUE THREAD

**Issue by janpio** [hzoo/contributors-on-github#34]
I just noticed this doesnt seem to do anything for me any more. Is this true for everyone or just me?

**Comment by oliviertassinari** [comment]
I have noticed the same.

**Comment by janpio** [comment]
Ok, then it is not me being too dumb - good. 

Probably Github changed something in their HTML structure. Will try to investigate later.

**Comment by hzoo** [comment]
Sorry about this, haven't had the time to look into it!

**Comment by janpio** [comment]
Don't worry, we all know how it is <3

If anyone ever looks into this, please leave the information you find out in this issue. Maybe we can fix it together.

**Comment by NdagiStanley** [comment]
Commenting here so that I can remember to see if I can give it time :smile:

**Comment by paulirish** [comment]
the fix was really easy. :)

its at https://github.com/hzoo/contributors-on-github/pull/36 in case it takes time to get merged and published.
cheers

**Comment by hzoo** [comment]
Thanks for all the input @janpio and fix @paulirish, commented in the PR as well, but seems like we gotta wait for a review since it's been too long since the last release 😛!

![image](https://user-images.githubusercontent.com/588473/108609175-45e93000-739a-11eb-944b-9b81fdc50272.png)

**Comment by paulirish** [comment]
Btw I got an email from github last night telling me the access_token as
queryparam is deprecated.

So ideally we also get a fix for that.

**Comment by paulirish** [comment]
Ah you're so good

https://github.com/hzoo/contributors-on-github/pull/38

Nice work!

**Comment by hzoo** [comment]
Ok it should be good now, got store approval https://chrome.google.com/webstore/detail/github-contributor-stats/cjbacdldhllelehomkmlniifaojgaeph?hl=en! found a gh actions setup from refined-github on adding a cron job, and also firefox should work now too!
