### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by sindresorhus** [hzoo/contributors-on-github#5]
Btw, GitHub is actively asking people not to prefix extensions with `github`, so I would recommend changing it now, rather than later. I had to change all my extensions. It's ok using GitHub in the name, just not first. E.g. I renamed `github-notifier` to `notifier-for-github`.

This could be named `contributors-on-github` or something.

**Comment by hzoo** [comment]
Ah ok had no idea, thanks!

**Comment by hzoo** [comment]
Done with https://github.com/hzoo/contributors-on-github/issues/9!
